"""
Canonical product model for LUAF publish targets (Swarms vs RapidAPI).

Designer output stays in the existing JSON shape; adapters map to each target.
"""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from typing import Any, Literal

PublishTarget = Literal["swarms", "rapidapi"]

# Extensible registry: (env token, short title, one-line description) — order defines CLI menu numbers.
PUBLISH_TARGET_REGISTRY: tuple[tuple[PublishTarget, str, str], ...] = (
    ("swarms", "Swarms marketplace", "swarms.world listing; optional Solana tokenization"),
    ("rapidapi", "RapidAPI-assisted bundle", "FastAPI + openapi.json; optional Fly.io deploy"),
)


def get_publish_target() -> PublishTarget:
    """Resolve publish target from env; default swarms for backward compatibility."""
    raw = (os.environ.get("LUAF_PUBLISH_TARGET") or "swarms").strip().lower()
    if raw in ("rapidapi", "rapid", "rapid_api"):
        return "rapidapi"
    return "swarms"


def _slug(s: str, max_len: int = 48) -> str:
    t = re.sub(r"[^a-zA-Z0-9]+", "-", (s or "agent").strip().lower()).strip("-")
    return (t or "agent")[:max_len]


@dataclass
class CanonicalProductModel:
    """Normalized artifact after designer parse_agent_payload (Swarms-shaped source)."""

    name: str
    ticker: str
    description: str
    agent_code: str
    use_cases: list[dict[str, str]]
    tags: str
    requirements: list[dict[str, str]]
    language: str
    is_free: bool = True
    raw_payload: dict[str, Any] = field(default_factory=dict)

    def slug(self) -> str:
        return _slug(self.name or self.ticker or "api")


def canonical_from_designer_payload(payload: dict[str, Any]) -> CanonicalProductModel:
    """Build canonical model from designer JSON (required keys already validated)."""
    use_cases_raw = payload.get("useCases") or []
    use_cases: list[dict[str, str]] = []
    if isinstance(use_cases_raw, list):
        for item in use_cases_raw:
            if isinstance(item, dict):
                use_cases.append(
                    {
                        "title": str(item.get("title") or ""),
                        "description": str(item.get("description") or ""),
                    }
                )
    req_raw = payload.get("requirements") or []
    requirements: list[dict[str, str]] = []
    if isinstance(req_raw, list):
        for item in req_raw:
            if isinstance(item, dict):
                requirements.append(
                    {
                        "package": str(item.get("package") or ""),
                        "installation": str(item.get("installation") or ""),
                    }
                )
    return CanonicalProductModel(
        name=str(payload.get("name") or "").strip(),
        ticker=str(payload.get("ticker") or "").strip(),
        description=str(payload.get("description") or "").strip(),
        agent_code=str(payload.get("agent") or ""),
        use_cases=use_cases,
        tags=str(payload.get("tags") or "").strip(),
        requirements=requirements,
        language=str(payload.get("language") or "python").strip(),
        is_free=bool(payload.get("is_free", True)),
        raw_payload=dict(payload),
    )


def rapid_openapi_spec(base_url: str, title: str, description: str) -> dict[str, Any]:
    """Minimal OpenAPI 3.0 document for the FastAPI wrapper (RapidAPI import)."""
    return {
        "openapi": "3.0.3",
        "info": {
            "title": title[:80] or "LUAF Agent API",
            "description": description[:2000] or "Generated by LUAF RapidAPI bundle.",
            "version": "1.0.0",
        },
        "servers": [{"url": base_url.rstrip("/") or "https://example.com"}],
        "paths": {
            "/health": {
                "get": {
                    "summary": "Health check",
                    "operationId": "health_check",
                    "responses": {"200": {"description": "OK"}},
                }
            },
            "/run": {
                "post": {
                    "summary": "Run agent subprocess with optional argv",
                    "operationId": "run_agent",
                    "requestBody": {
                        "required": False,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "argv": {
                                            "type": "array",
                                            "items": {"type": "string"},
                                            "description": 'Extra CLI args after script, e.g. ["--task","my task"]',
                                        }
                                    },
                                }
                            }
                        },
                    },
                    "responses": {
                        "200": {
                            "description": "Subprocess result",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "properties": {
                                            "ok": {"type": "boolean"},
                                            "returncode": {"type": "integer"},
                                            "stdout": {"type": "string"},
                                            "stderr": {"type": "string"},
                                        },
                                    }
                                }
                            },
                        }
                    },
                }
            },
        },
    }
