"""
RapidAPI-assisted publishing: FastAPI wrapper, OpenAPI artifact, optional Fly.io deploy.

Does not call RapidAPI's portal APIs; produces a bundle + checklist for manual listing.
"""
from __future__ import annotations

import json
import os
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from loguru import logger

from luaf.publishing.model import CanonicalProductModel, canonical_from_designer_payload, rapid_openapi_spec

FASTAPI_APP_PY = '''\
"""LUAF-generated HTTP wrapper for RapidAPI listing. Runs generated_agent.py as subprocess."""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

ROOT = Path(__file__).resolve().parent
AGENT_SCRIPT = ROOT / "generated_agent.py"


class RunBody(BaseModel):
    argv: list[str] = Field(
        default_factory=list,
        description='Extra argv after script name, e.g. ["--task", "periodic_refresh"]',
    )


class RunResponse(BaseModel):
    ok: bool
    returncode: int
    stdout: str
    stderr: str


app = FastAPI(
    title=os.environ.get("LUAF_API_TITLE", "LUAF Agent API"),
    version="1.0.0",
    description=os.environ.get("LUAF_API_DESC", "Agent subprocess API"),
)


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "agent": AGENT_SCRIPT.name}


@app.post("/run", response_model=RunResponse)
def run_agent(body: RunBody) -> RunResponse:
    if not AGENT_SCRIPT.is_file():
        raise HTTPException(status_code=500, detail="generated_agent.py missing")
    cmd = [sys.executable, str(AGENT_SCRIPT), *body.argv]
    timeout = int(os.environ.get("LUAF_API_TIMEOUT", "600"))
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(ROOT),
            env=os.environ.copy(),
        )
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=504, detail="agent timed out") from None
    out_cap = 100000
    return RunResponse(
        ok=proc.returncode == 0,
        returncode=proc.returncode,
        stdout=(proc.stdout or "")[:out_cap],
        stderr=(proc.stderr or "")[:out_cap],
    )
'''

DOCKERFILE = """# LUAF RapidAPI bundle
FROM python:3.11-slim
WORKDIR /app
COPY requirements_api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY generated_agent.py app.py ./
ENV PORT=8080
EXPOSE 8080
CMD uvicorn app:app --host 0.0.0.0 --port 8080
"""


def _requirements_lines(canonical: CanonicalProductModel) -> list[str]:
    base = ["fastapi>=0.109.0", "uvicorn[standard]>=0.27.0", "pydantic>=2.0"]
    seen = {p.lower().split("[")[0] for p in base}
    lines = list(base)
    for req in canonical.requirements:
        pkg = (req.get("package") or "").strip()
        if not pkg:
            continue
        key = pkg.lower().split("[")[0]
        if key in ("fastapi", "uvicorn", "pydantic"):
            continue
        if key not in seen:
            seen.add(key)
            lines.append(pkg)
    return lines


def _fly_toml(app_name: str, region: str) -> str:
    return f"""# Generated by LUAF — set app name via LUAF_FLY_APP_NAME
app = "{app_name}"
primary_region = "{region}"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
"""


def _assisted_publish_md(
    bundle_dir: Path,
    public_url: Optional[str],
    canonical: CanonicalProductModel,
) -> str:
    base = (public_url or "https://YOUR_DEPLOYED_HOST").rstrip("/")
    return f"""# RapidAPI assisted publish — {canonical.name}

## 1. Deploy this API

Bundle directory: `{bundle_dir}`

### Option A — Fly.io (LUAF-managed)

1. Install [flyctl](https://fly.io/docs/hands-on/install-flyctl/).
2. Set `LUAF_FLY_API_TOKEN` and `LUAF_FLY_APP_NAME` in `.env`.
3. Run `luaf run` with `LUAF_PUBLISH_TARGET=rapidapi` and `LUAF_DRY_RUN=0` (or deploy manually):

```bash
cd "{bundle_dir}"
flyctl auth login   # if not using token
flyctl launch --no-deploy --name YOUR_APP --region iad   # first time only
flyctl deploy --remote-only
```

Expected URL: `https://<LUAF_FLY_APP_NAME>.fly.dev`

### Option B — Any container host

Build and run the Dockerfile; expose port **8080**. Set `LUAF_API_TITLE` / `LUAF_API_DESC` if desired.

## 2. Import into RapidAPI Hub

1. Open [RapidAPI Provider Dashboard](https://rapidapi.com/provider/dashboard).
2. **Add New API** → **Import** → upload `openapi.json` from this bundle.
3. Set **Base URL** to: `{base}`
4. Map **GET /health** and **POST /run**; test from the Hub.
5. Add **pricing** (e.g. per-request) and submit for listing.

## 3. Call contract

- `POST /run` JSON body: `{{"argv": ["--task", "your task text"]}}`  
  Appends arguments after `generated_agent.py` (your agent should keep CLI args optional).

## Files in this bundle

| File | Purpose |
|------|---------|
| `generated_agent.py` | Designer output (your agent) |
| `app.py` | FastAPI wrapper |
| `requirements_api.txt` | Pip deps for the container |
| `openapi.json` | Import into RapidAPI |
| `rapid_listing.json` | Metadata hints |
| `Dockerfile` | Container image |
| `fly.toml` | Fly.io config (optional) |
"""


def load_rapid_registry(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        d = json.loads(path.read_text(encoding="utf-8"))
        return d if isinstance(d, list) else []
    except (json.JSONDecodeError, OSError):
        return []


def append_rapid_registry(
    path: Path,
    *,
    name: str,
    ticker: str,
    bundle_path: str,
    public_url: Optional[str],
    published_at: Optional[str] = None,
) -> None:
    reg = load_rapid_registry(path)
    entry: dict[str, Any] = {
        "name": name,
        "ticker": ticker,
        "bundle_path": bundle_path,
        "public_url": public_url,
        "listing_url": "https://rapidapi.com/provider/dashboard",
    }
    if published_at:
        entry["published_at"] = published_at
    reg.append(entry)
    fd, tmp = tempfile.mkstemp(prefix="luaf_rapid_", suffix=".json", dir=path.parent, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(json.dumps(reg, indent=2))
        os.replace(tmp, path)
    except OSError:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def write_rapid_bundle(
    canonical: CanonicalProductModel,
    bundle_dir: Path,
    *,
    placeholder_base_url: str = "https://example.com",
) -> Path:
    """Write all bundle files; returns bundle_dir."""
    bundle_dir.mkdir(parents=True, exist_ok=True)
    (bundle_dir / "generated_agent.py").write_text(canonical.agent_code, encoding="utf-8")
    (bundle_dir / "app.py").write_text(FASTAPI_APP_PY, encoding="utf-8")
    req_txt = "\n".join(_requirements_lines(canonical)) + "\n"
    (bundle_dir / "requirements_api.txt").write_text(req_txt, encoding="utf-8")
    (bundle_dir / "Dockerfile").write_text(DOCKERFILE, encoding="utf-8")
    fly_app = (os.environ.get("LUAF_FLY_APP_NAME") or canonical.slug()).strip().replace("_", "-")[:40]
    region = (os.environ.get("LUAF_FLY_REGION") or "iad").strip() or "iad"
    (bundle_dir / "fly.toml").write_text(_fly_toml(fly_app, region), encoding="utf-8")
    title = canonical.name or canonical.ticker or "LUAF API"
    spec = rapid_openapi_spec(placeholder_base_url, title, canonical.description)
    (bundle_dir / "openapi.json").write_text(json.dumps(spec, indent=2), encoding="utf-8")
    listing = {
        "name": canonical.name,
        "ticker": canonical.ticker,
        "short_description": canonical.description[:500],
        "tags": canonical.tags,
        "use_cases": canonical.use_cases,
        "base_url_placeholder": placeholder_base_url,
        "openapi_file": "openapi.json",
        "notes": "After deploy, re-export openapi.json with real servers URL or edit servers[0].url in Hub.",
    }
    (bundle_dir / "rapid_listing.json").write_text(json.dumps(listing, indent=2), encoding="utf-8")
    assisted = _assisted_publish_md(bundle_dir, None, canonical)
    (bundle_dir / "ASSISTED_PUBLISH.md").write_text(assisted, encoding="utf-8")
    logger.info("RapidAPI bundle written to {}", bundle_dir)
    return bundle_dir


def attempt_fly_deploy(bundle_dir: Path) -> tuple[bool, str, Optional[str]]:
    """
    Run flyctl deploy if LUAF_FLY_API_TOKEN and LUAF_FLY_APP_NAME are set.
    Returns (ok, message, public_url).
    """
    token = (os.environ.get("LUAF_FLY_API_TOKEN") or "").strip()
    app = (os.environ.get("LUAF_FLY_APP_NAME") or "").strip()
    if not token or not app:
        return False, "LUAF_FLY_API_TOKEN and LUAF_FLY_APP_NAME not both set; skipped Fly deploy.", None
    env = os.environ.copy()
    env["FLY_API_TOKEN"] = token
    cmd = ["flyctl", "deploy", "--remote-only", "--yes"]
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(bundle_dir),
            env=env,
            capture_output=True,
            text=True,
            timeout=3600,
        )
    except FileNotFoundError:
        return False, "flyctl not found in PATH; install Fly.io CLI.", None
    except subprocess.TimeoutExpired:
        return False, "flyctl deploy timed out.", None
    out = (proc.stdout or "") + "\n" + (proc.stderr or "")
    if proc.returncode != 0:
        return False, out[-8000:] or "flyctl deploy failed", None
    public_url = f"https://{app}.fly.dev"
    return True, out[-4000:], public_url


def publish_rapid_assisted(
    payload: dict[str, Any],
    *,
    dry_run: bool,
    registry_path: Path,
    bundles_base: Optional[Path] = None,
) -> dict[str, Any]:
    """
    Build RapidAPI bundle; optionally Fly deploy when not dry_run and token configured.

    Returns a dict compatible with callers that expect listing_url / id fields.
    """
    canonical = canonical_from_designer_payload(payload)
    base = bundles_base or Path(os.environ.get("LUAF_RAPID_BUNDLES_DIR") or "rapid_bundles")
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    bundle_dir = base / f"{canonical.slug()}_{stamp}"
    placeholder = (os.environ.get("LUAF_RAPID_PLACEHOLDER_BASE_URL") or "https://example.com").strip()
    write_rapid_bundle(canonical, bundle_dir, placeholder_base_url=placeholder)

    result: dict[str, Any] = {
        "id": bundle_dir.name,
        "listing_url": "https://rapidapi.com/provider/dashboard",
        "bundle_path": str(bundle_dir.resolve()),
        "token_address": None,
        "dry_run": dry_run,
    }

    public_url: Optional[str] = None
    deploy_msg = ""

    managed = (os.environ.get("LUAF_MANAGED_DEPLOY") or "fly").strip().lower()
    if not dry_run and managed in ("fly", "fly.io"):
        ok, msg, public_url = attempt_fly_deploy(bundle_dir)
        deploy_msg = msg
        if ok and public_url:
            logger.info("Fly deploy OK: {}", public_url)
            spec = rapid_openapi_spec(public_url, canonical.name or "API", canonical.description)
            (bundle_dir / "openapi.json").write_text(json.dumps(spec, indent=2), encoding="utf-8")
            assisted = _assisted_publish_md(bundle_dir, public_url, canonical)
            (bundle_dir / "ASSISTED_PUBLISH.md").write_text(assisted, encoding="utf-8")
        else:
            logger.warning("Fly deploy skipped or failed: {}", msg[:500])
    elif dry_run:
        logger.info("RapidAPI path: dry_run — bundle only, no Fly deploy.")

    result["public_url"] = public_url
    result["deploy_log_tail"] = deploy_msg[-2000:] if deploy_msg else ""

    if not dry_run:
        published_at = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
        append_rapid_registry(
            registry_path,
            name=canonical.name,
            ticker=canonical.ticker,
            bundle_path=str(bundle_dir.resolve()),
            public_url=public_url,
            published_at=published_at,
        )
        if public_url:
            result["listing_url"] = public_url

    logger.info("RapidAPI assisted publish complete. See ASSISTED_PUBLISH.md in bundle.")
    return result
